### ISSUE TITLE
Clean and Refactor Code

### ISSUE THREAD

**Issue by Bluju** [PNW-CS-Club/gkstudyhall#71]
Remove all zombie code (old code that is commented out) because we can always look back at previous versions of our code. Refactor certain classes with questionable implementation.

**Comment by gadahl** [comment]
- stop making StateMachine only live in StateTester
- turn StateMachine into a MonoBehavior
- turn TraitHandler back into a MonoBehavior
- make sure to check the inspector for null object references, etc
