### ISSUE TITLE
Character Select Menu

### ISSUE THREAD

**Issue by Marco-Minetti** [PNW-CS-Club/gkstudyhall#87]
Add a way to select a card for a player

**Comment by gadahl** [comment]
@Marco-Minetti I'm not seeing the commits you made, I think you would have to push them to origin for everyone else to see them

There's probably a specific command for that on the CLI, but I usually use the desktop apps to do

**Comment by Marco-Minetti** [comment]
@gadahl Thanks for telling me. I have push the commit. Let me know if you are able to see it.

**Comment by gadahl** [comment]
Yep it looks like it worked correctly 👍

**Comment by gadahl** [comment]
oh @Marco-Minetti you will probably have to watch out and make sure to pull any changes on your branch from github. I just made a little commit to fix some whitespace stuff

**Comment by Bluju** [comment]
In order to make it so that the selected card is assigned to the player when the game starts we need to update the player instances (Player1, Player2, Player3, Player4) when a new card is assigned to them. These PlayerSO instances are added to the player list when the start button is clicked.

**Comment by Bluju** [comment]
I think a pull request can be made for this branch at this point. @Marco-Minetti, make any final changes then create a pull request for this issue. If you need any help feel free to let us know.
